# Лабораторная 2. Решение СЛАУ различными методами (пункт г).

In [4]:
import numpy as np
import matplotlib.pyplot as plt

In [5]:
%matplotlib widget

In [92]:
n = 100
A = np.zeros((n, n))
F = np.zeros((n, 1))

for i in range(0, n):
    if (i == 0):
        for j in range(0, n):
            A[0, j] = 1
        continue 

    if (i == n - 1):
        A[n - 1, n - 2] = 1
        A[n - 1, n - 1] = 1
        continue

    A[i, i - 1] = 1
    A[i, i    ] = 10
    A[i, i + 1] = 1

for i in range(0, n):
    F[i, 0] = n - i
    
"""
A = np.matrix([[10., 6., 2., 0.],
              [5., 1., -2., 4.],
              [3., 5., 1., -1.],
              [0., 6., -2., 2.]])
    
F = np.matrix([[25.], [14.], [10.], [8.]])
"""

print(A)
print(F)

[[ 1.  1.  1. ...  1.  1.  1.]
 [ 1. 10.  1. ...  0.  0.  0.]
 [ 0.  1. 10. ...  0.  0.  0.]
 ...
 [ 0.  0.  0. ... 10.  1.  0.]
 [ 0.  0.  0. ...  1. 10.  1.]
 [ 0.  0.  0. ...  0.  1.  1.]]
[[100.]
 [ 99.]
 [ 98.]
 [ 97.]
 [ 96.]
 [ 95.]
 [ 94.]
 [ 93.]
 [ 92.]
 [ 91.]
 [ 90.]
 [ 89.]
 [ 88.]
 [ 87.]
 [ 86.]
 [ 85.]
 [ 84.]
 [ 83.]
 [ 82.]
 [ 81.]
 [ 80.]
 [ 79.]
 [ 78.]
 [ 77.]
 [ 76.]
 [ 75.]
 [ 74.]
 [ 73.]
 [ 72.]
 [ 71.]
 [ 70.]
 [ 69.]
 [ 68.]
 [ 67.]
 [ 66.]
 [ 65.]
 [ 64.]
 [ 63.]
 [ 62.]
 [ 61.]
 [ 60.]
 [ 59.]
 [ 58.]
 [ 57.]
 [ 56.]
 [ 55.]
 [ 54.]
 [ 53.]
 [ 52.]
 [ 51.]
 [ 50.]
 [ 49.]
 [ 48.]
 [ 47.]
 [ 46.]
 [ 45.]
 [ 44.]
 [ 43.]
 [ 42.]
 [ 41.]
 [ 40.]
 [ 39.]
 [ 38.]
 [ 37.]
 [ 36.]
 [ 35.]
 [ 34.]
 [ 33.]
 [ 32.]
 [ 31.]
 [ 30.]
 [ 29.]
 [ 28.]
 [ 27.]
 [ 26.]
 [ 25.]
 [ 24.]
 [ 23.]
 [ 22.]
 [ 21.]
 [ 20.]
 [ 19.]
 [ 18.]
 [ 17.]
 [ 16.]
 [ 15.]
 [ 14.]
 [ 13.]
 [ 12.]
 [ 11.]
 [ 10.]
 [  9.]
 [  8.]
 [  7.]
 [  6.]
 [  5.]
 [  4.]
 [  3.]
 [  2.]
 [  1.]]


In [93]:
def gauss_elimination(A, F):
    """
    Реализует метод Гаусса с выбором главного элемента для системы вида AU = F.

    Args:
        A: Матрица коэффициентов системы (numpy.matrix).
        F: Вектор свободных членов (numpy.matrix).

    Returns:
        Вектор решений системы (numpy.matrix) или None, если система не имеет решений.
    """

    n = A.shape[0]
    augmented_matrix = np.concatenate((A, F), axis=1) # Расширенная матрица

    for i in range(n):
        # Поиск главного элемента в матрице
        max_index = np.argmax(np.abs(augmented_matrix[i:, i])) + i
        
        # Перестановка строк
        augmented_matrix[[i, max_index], :] = augmented_matrix[[max_index, i], :]

        # Проверка на нулевой главный элемент
        if augmented_matrix[i, i] == 0:
            return None # Система не имеет решений

        # Нормализация строки
        augmented_matrix[i, :] /= augmented_matrix[i, i]

        # Обнуление элементов ниже главного элемента
        for j in range(i + 1, n):
            augmented_matrix[j, :] -= augmented_matrix[i, :] * augmented_matrix[j, i]

    # Обратный ход
    U = np.zeros((n, 1))

    for i in range(n - 1, -1, -1):
        U[i, 0] = augmented_matrix[i, n]
        for j in range(i - 1, -1, -1):
            augmented_matrix[j, n] -= augmented_matrix[j, i] * U[i, 0]

    return U

In [98]:
u = gauss_elimination(A, F)

print(np.dot(A, u))

[[100.]
 [ 99.]
 [ 98.]
 [ 97.]
 [ 96.]
 [ 95.]
 [ 94.]
 [ 93.]
 [ 92.]
 [ 91.]
 [ 90.]
 [ 89.]
 [ 88.]
 [ 87.]
 [ 86.]
 [ 85.]
 [ 84.]
 [ 83.]
 [ 82.]
 [ 81.]
 [ 80.]
 [ 79.]
 [ 78.]
 [ 77.]
 [ 76.]
 [ 75.]
 [ 74.]
 [ 73.]
 [ 72.]
 [ 71.]
 [ 70.]
 [ 69.]
 [ 68.]
 [ 67.]
 [ 66.]
 [ 65.]
 [ 64.]
 [ 63.]
 [ 62.]
 [ 61.]
 [ 60.]
 [ 59.]
 [ 58.]
 [ 57.]
 [ 56.]
 [ 55.]
 [ 54.]
 [ 53.]
 [ 52.]
 [ 51.]
 [ 50.]
 [ 49.]
 [ 48.]
 [ 47.]
 [ 46.]
 [ 45.]
 [ 44.]
 [ 43.]
 [ 42.]
 [ 41.]
 [ 40.]
 [ 39.]
 [ 38.]
 [ 37.]
 [ 36.]
 [ 35.]
 [ 34.]
 [ 33.]
 [ 32.]
 [ 31.]
 [ 30.]
 [ 29.]
 [ 28.]
 [ 27.]
 [ 26.]
 [ 25.]
 [ 24.]
 [ 23.]
 [ 22.]
 [ 21.]
 [ 20.]
 [ 19.]
 [ 18.]
 [ 17.]
 [ 16.]
 [ 15.]
 [ 14.]
 [ 13.]
 [ 12.]
 [ 11.]
 [ 10.]
 [  9.]
 [  8.]
 [  7.]
 [  6.]
 [  5.]
 [  4.]
 [  3.]
 [  2.]
 [  1.]]


In [7]:
def show_plot(h, func, derivative_func, func_name):
    x_0 = 0
    dy_0 = derivative_func(x_0)
        
    plt.figure(figsize=[8, 4])

    eps_1 = get_error(func, derivative_func, method_1, h, np.linspace(0, np.pi, 100))
    eps_2 = get_error(func, derivative_func, method_2, h, np.linspace(0, np.pi, 100))
    eps_3 = get_error(func, derivative_func, method_3, h, np.linspace(0, np.pi, 100))
    eps_4 = get_error(func, derivative_func, method_4, h, np.linspace(0, np.pi, 100))
    eps_5 = get_error(func, derivative_func, method_5, h, np.linspace(0, np.pi, 100))
    
    plt.plot(h, eps_1, label="Метод 1")
    plt.plot(h, eps_2, label="Метод 2")
    plt.plot(h, eps_3, label="Метод 3")
    plt.plot(h, eps_4, label="Метод 4")
    plt.plot(h, eps_5, label="Метод 5")
    
    plt.loglog()
    plt.xlabel("$h(n) = \\frac{2}{2^n}$")
    plt.ylabel("Погрешность")
    plt.title("Абсолютная погрешность дифференцирования функции: "+func_name)
    plt.grid()
    plt.legend()
    plt.show()